### ISSUE TITLE
Crashes when trying to restart with --log

### ISSUE THREAD

**Issue by WebFreak001** [Extrawurst/forever-d#10]
```
forever-d --log log.txt --err errlog.txt ./app &
killall app
-- 2017-Feb-09 09:24:03.61352 -- Process Ended. Exitcode: 0
-- 2017-Feb-09 09:24:03.613601 -- Starting: './app'
object.Exception@/build/ldc-I3nwWj/ldc-0.17.1/runtime/phobos/std/stdio.d(1709): Attempting to call getFP() on an unopened file
----------------

[1]+  Exit 1                  forever-d --log log.txt --err errlog.txt ./app
```

And app didn't restart, instead forever-d crashed

**Comment by Extrawurst** [comment]
ok i will look into that, as a workaround you can run it with `forever-d ... > server.log &`

**Comment by WebFreak001** [comment]
I think it worked once, not sure if I used pipes when it worked with restarting. But I had this bug basically since I started using forever-d, which was really destroying the point of "forever"

**Comment by extrawurst** [comment]
should work now, i could reproduce it and it works now... dont ask me what changed in phobos but it used to work before...
